"""empty message

Revision ID: 229007769cdf
Revises: ed2bad2bbb55
Create Date: 2021-06-25 14:31:37.698236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229007769cdf'
down_revision = 'ed2bad2bbb55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('courses', sa.Column('lesson_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courses', 'lesson', ['lesson_id'], ['id'])
    op.drop_column('courses', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('name', sa.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'lesson_id')
    op.drop_table('lesson')
    # ### end Alembic commands ###
