"""empty message

Revision ID: a9df30d13bec
Revises: 50c80c471e77
Create Date: 2021-06-26 22:24:39.897604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9df30d13bec'
down_revision = '50c80c471e77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('text', sa.String(), nullable=False))
    op.add_column('posts', sa.Column('published_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'published_at')
    op.drop_column('posts', 'text')
    # ### end Alembic commands ###
